#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: register

import os
import cgitb; cgitb.enable()
import page_functions
import cgi
form = cgi.FieldStorage()
name = form.getfirst('name', None)
pass1 = form.getfirst('pass1', None)
pass2 = form.getfirst('pass2', None)

import MySQLdb
db = MySQLdb.connect(host='localhost', port=1234,
                     user='root', passwd='', db='quickShare')
cursor = db.cursor()
errors = ''
what_to_print  = """
<form method=post action=register><table>
<tr><td>Name: </td><td><input type=text name=name /></td></tr>
<tr><td>Password: </td><td><input type=password name=pass1 /></td></tr>
<tr><td>Confirm Password: </td><td><input type=password name=pass2 /></td></tr>
<tr><td><input type=submit value=Register! /></td></tr>
</table></form>
"""
if name:
    errors += 'Error. Registration not successful.</br>'
    if name  < 5:
        errors += 'Username must be at least 5 characters</br>'
    elif cursor.execute("SELECT * FROM User WHERE username='%s'" % name) >= 1:
        errors += 'The user already exists.</br>'
    elif pass1 and pass2:
        if len(pass1) < 5:
            errors += 'Password must be at least 5 characters</br>'
        elif pass1 == pass2:
            cursor.execute("Insert User set username='%s', password='%s'" % (name,pass1))
            if not os.path.exists('/var/www/html/images/%s' %name):
                os.system("mkdir /var/www/html/images/%s" %name)
            what_to_print = name
            what_to_print += " your registration was successful!"
            errors = ''
        else:
            errors += "Error. Passwords do not match"
print r"""Content-Type: text/html;charset=utf-8

<html>
%s
<body>
%s
%s </br>
%s
</body>
</html>
""" % (page_functions.header(), page_functions.topLinks(), errors, what_to_print)
db.commit()
db.close()
