#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: register

import cgitb; cgitb.enable()
import page_functions
import cgi
form = cgi.FieldStorage()
name = form.getfirst('name', None)
pass1 = form.getfirst('pass1', None)
pass2 = form.getfirst('pass2', None)

import MySQLdb
db = MySQLdb.connect(host='localhost', port=1234,
                     user='root', passwd='', db='quickShare')
cursor = db.cursor()

result = ''
what_to_print  = """
<form method=post action=register><table>
<tr><td>Name: </td><td><input type=text name=name /></td></tr>
<tr><td>Password: </td><td><input type=text name=pass1 /></td></tr>
<tr><td>Confirm Password: </td><td><input type=text name=pass2 /></td></tr>
<tr><td><input type=submit value=Register! /></td></tr>
</table></form>
"""
if name:
    result = "Error. Registration not successful."
    if pass1 and pass2:
        if pass1 == pass2:
            what_to_print = name
            what_to_print += " registration successful "
            what_to_print += "<a href=login>click here</a>"
            what_to_print += " to go to login page!"
            result = ''
        else:
            result = "Error. Passwords do not match"
print r"""Content-Type: text/html;charset=utf-8

<html>
%s
<body>
%s
%s </br>
%s
</body>
</html>
""" % (page_functions.header(), page_functions.topLinks(), result, what_to_print)
