#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: save_file

import cgitb; cgitb.enable()
import page_functions
import cgi
form = cgi.FieldStorage()
username = form.getfirst('session', '')
rename = form.getfirst('name', '')
result = ''
img = ''
import os
import MySQLdb
db = MySQLdb.connect(host='localhost', port=1234,
                     user='root', passwd='', db='quickShare')
cursor = db.cursor()
# Get filename here.
fileitem = form['filename']
# Test if the file was uploaded
if fileitem.filename:
    fn = os.path.basename(fileitem.filename)
    file_root = '/var/www/html'
    file_path = '/images/%s/%s' % (username,fn)
    file_savepath = file_root + file_path
    userID = -1
    if cursor.execute("SELECT ID FROM User WHERE username='%s'" % username) >= 1:
        userID = cursor.fetchone()[0]
    if userID == -1:
        message = 'This user that is logged in right now does not exist'
    else:
        if cursor.execute("SELECT * FROM Image WHERE user_ID='%s' AND image_name='%s'" % (userID,fn)) >= 1:
            message = 'The image already exists'
        else:
            f = file(file_savepath, 'wb')
            while 1:
                chunk = fileitem.file.read(1024)
                if not chunk:
                    break
                f.write(chunk)
            f.close()
            ex = "Insert Image set image_name='%s', file_path='%s'" %(fn,file_path)
            ex += ", user_id='%s'" % userID
            cursor.execute(ex)
            message = 'The file "' + fn + '" was uploaded successfully'

print r"""Content-Type: text/html;charset=utf-8

<html>
%s
<body>
%s
</br>
%s
%s
</body>
</html>
""" % (page_functions.header(), page_functions.topLinks(username), message, img)
db.commit()
db.close()
