#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: save_file

import cgitb; cgitb.enable()
import page_functions
import cgi
form = cgi.FieldStorage()
username = form.getfirst('session', '')
rename = form.getfirst('name', '')
result = ''
img = ''
import osimport MySQLdb
db = MySQLdb.connect(host='localhost', port=1234,
                     user='root', passwd='', db='quickShare')
cursor = db.cursor()
# Get filename here.
fileitem = form['filename']
# Test if the file was uploaded
if fileitem.filename:
    fn = os.path.basename(fileitem.filename)
    file_root = '/var/www/html'
    file_path = '/images/%s/%s' % (username,fn)
    file_savepath = file_root + file_path
    f = file(file_savepath, 'wb')
    while 1:
        chunk = fileitem.file.read(1024)
        if not chunk:
            break
        f.write(chunk)
    f.close()
    img += '<img src="' + file_path + '" width=300 height=300/>\n'
    message = 'The file "' + fn + '" was uploaded successfully'
else:
    message = 'No file was uploaded'

print r"""Content-Type: text/html;charset=utf-8

<html>
%s
<body>
%s
</br>
%s
%s
</body>
</html>
""" % (page_functions.header(), page_functions.topLinks(username), message, img)
