#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: uploadPhoto

import cgitb; cgitb.enable()
import page_functions
import cgi
form = cgi.FieldStorage()
username = form.getfirst('session', '')
result = ''

print r"""Content-Type: text/html;charset=utf-8

<html>
%s
<body>
%s
</br>
<form enctype=multipart/form-data
action=save_file?session=%s method=post>
<p>File: <input type=file name='filename' accept='/images/*'/></p>
<p><input type=submit value=Upload /></p>
</form>
</body>
</html>
""" % (page_functions.header(), page_functions.topLinks(username), username)
